### ISSUE TITLE
Relax the R >= 3.5 requirement

### ISSUE THREAD

**Issue by gaborcsardi** [traversc/qs#11]
What would it take to support R >= 3.2?

**Comment by traversc** [comment]
Just deleting the alt-rep stuff.  I'm using it because I think the string cache is unnecessarily slow, but someone else pointed out that it can blow up memory.

**Comment by gaborcsardi** [comment]
What do you think about having an ALTREP free implementation for older R
versions?

**Comment by traversc** [comment]
Hi Gabor, I updated the github version so that it works with R < 3.5.  Instead of having two different versions, I used preprocessor macros to comment out alt-rep stuff if it detects R < 3.5.  

Tested it out with R 3.4 on windows.

**Comment by gaborcsardi** [comment]
Thanks!
