### ISSUE TITLE
Note about AGPL-3 license

### ISSUE THREAD

**Issue by hadley** [traversc/qs#13]
AGPL-3 is sufficiently unusual that I think it's worth a brief note in the readme. It's likely to make it impossible for people to use inside many companies (for example, both google and facebook forbid the use of AGPL software).

**Comment by traversc** [comment]
Thanks for the info.  What would you recommend?

**Comment by hadley** [comment]
An ideal world, I'd recommend avoid using AGPL-3 just because it's relatively unknown, and bigger companies are generally [concerned about it](https://opensource.google.com/docs/using/agpl-policy/). If you've picked it deliberately, then I think you should at least just note the license on the README, and maybe point to something like <https://www.gnu.org/licenses/why-affero-gpl.html>

**Comment by traversc** [comment]
I've changed the license to standard GPL-3.  Thanks again for the heads up.

**Comment by hadley** [comment]
Awesome, thanks!
