### ISSUE TITLE
Is it possible to use `qs` to compress an object and not serialize to disk?

### ISSUE THREAD

**Issue by xiaodaigh** [traversc/qs#16]
I imagine a `qs` function called `compress`

```r
compress_obj = compress(large_object)
```
and that `compress_obj` is still in memory. Why would I want that? It's because I can use it together with `future` and pass compressed object back and forth worker sessions.

**Comment by traversc** [comment]
Yes, there are two functions for that:

`qserialize` and `qdeserialize`.
