### ISSUE TITLE
fatal error: R_ext/Altrep.h: No such file or directory

### ISSUE THREAD

**Issue by csrvermaak** [traversc/qs#3]
Hi

I'm very excited about this package, sounds impressive.

Having some issues installing though. I succesfully installed the latest version of both dependencies:

 * `Rcpp - 1.0.1`
 * `RApiSerialise 0.1.0`

Then downloaded the latest package source: `qs_0.14.1.tar.gz`

When I install from package source, I get the following:

```
> install.packages("C:/Users/Rvermaak/Downloads/qs_0.14.1.tar.gz", repos = NULL, type = "source")
Installing package into ‘C:/Users/Rvermaak/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'qs' ...
** package 'qs' successfully unpacked and MD5 sums checked

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs
c:/RBuildTools/3.5/mingw_64/bin/g++ -m64 -std=gnu++11 -I"C:/PROGRA~1/MICROS~1/ROPEN~1/R-35~1.0/include" -DNDEBUG -I. -IZSTD -IZSTD/common -IZSTD/decompress -IZSTD/compress -ILZ4 -I"C:/Users/Rvermaak/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Rvermaak/Documents/R/win-library/3.5/RApiSerialize/include"   -I"C:/swarm/workspace/External-R-3.5.0/vendor/extsoft/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
c:/RBuildTools/3.5/mingw_64/bin/g++ -m64 -std=gnu++11 -I"C:/PROGRA~1/MICROS~1/ROPEN~1/R-35~1.0/include" -DNDEBUG -I. -IZSTD -IZSTD/common -IZSTD/decompress -IZSTD/compress -ILZ4 -I"C:/Users/Rvermaak/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/Rvermaak/Documents/R/win-library/3.5/RApiSerialize/include"   -I"C:/swarm/workspace/External-R-3.5.0/vendor/extsoft/include"     -O2 -Wall  -mtune=core2 -c qs_functions.cpp -o qs_functions.o
In file included from qs_functions.cpp:21:0:
qs_header.h:59:26: fatal error: R_ext/Altrep.h: No such file or directory
 #include <R_ext/Altrep.h>
                          ^
compilation terminated.
make: *** [C:/PROGRA~1/MICROS~1/ROPEN~1/R-35~1.0/etc/x64/Makeconf:215: qs_functions.o] Error 1
ERROR: compilation failed for package 'qs'
* removing 'C:/Users/Rvermaak/Documents/R/win-library/3.5/qs'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘C:/Users/Rvermaak/Downloads/qs_0.14.1.tar.gz’ had non-zero exit status
> 
```

Any ideas, please?

**Comment by csrvermaak** [comment]
I found this [purplecat blog](https://purrple.cat/blog/2018/10/14/altrep-and-cpp/), which states

_Unfortunately in R 3.5.0, the Altrep.h is not C++ friendly, so you need to be careful when you include it._

Does this mean qs isn't compatible with R3.5.0?

**Comment by traversc** [comment]
Yes, the main package isn't compatible with R before 3.5, but I have an earlier version that is:

**Comment by csrvermaak** [comment]
Thanks for getting back to me, appreciated.

I am actually on R3.5.0, so should be compatible?

**Comment by traversc** [comment]
In that case, I am not sure, but please try: 

`install.packages("qs")`

This is pre-compiled for windows on CRAN.  The github version is a bit of a development version, so CRAN would be better tested.

**Comment by csrvermaak** [comment]
I think I see the issue.  I am using Microsoft R Open, and install packages from MRAN.

There isn't a binary for `qs` on MRAN, hence I had to compile from source:

![image](https://user-images.githubusercontent.com/6738800/55062354-8476f280-507e-11e9-9bee-40fde95870a2.png)

**Comment by csrvermaak** [comment]
Hmm - from CRAN:

```
install.packages("qs")
Installing package into ‘C:/Users/Rvermaak/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘qs’ is not available (for R version 3.5.0)
Warning in install.packages :
  unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.5:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.5/PACKAGES'
```

**Comment by csrvermaak** [comment]
I see you build the CRAN packages using R3.5.3. Not to worry, I'll build from source, having manually copied the Altrep.h file to the correct folder.

```
library(qs)
Error: package or namespace load failed for ‘qs’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘RApiSerialize’
In addition: Warning message:
package ‘qs’ was built under R version 3.5.3 
```


PS - The speed improvement is GREAT!!! Thanks!

**Comment by traversc** [comment]
I see, Microsoft R open  complicates things, since they don’t keep quite up to date.  Iit may be something weird with MRO not finding the right headers, not sure.

Sorry I don’t know what the issue is, but I’ll troubleshoot and try to reproduce it later.  In the mean time, the version for R 3.4 should definitely work.

**Comment by csrvermaak** [comment]
Thanks - I've compile from source for now, manually found and copied the Altrep.h file.

The speed improvements are FANTASTIC! Thanks :)
