### ISSUE TITLE
rpois arguments

### ISSUE THREAD

**Issue by r2evans** [traversc/qs#32]
In your vignette and tests, you use `rpois(100, 5e6)` along with `rnorm(5e6)`. The call to `rpois` is producing only 100 random samples; `data.frame` won't complain because 100 cleanly recycles into 5e6.

(I doubt this has any influence on the benchmark or results, but the code is inconsistent.)

**Comment by traversc** [comment]
Thanks for pointing that out.  Will be sure to fix it next time ;)

**Comment by traversc** [comment]
Hey, I fixed that typo and took the opportunity to update the benchmark. Should be on CRAN as well.
