### ISSUE TITLE
Wrapper to replace base save and load operations

### ISSUE THREAD

**Issue by superchordate** [traversc/qs#33]
It'd be awesome if there were qs versions of the save and load operations from base, where you can give a file argument and a bunch of objects (also as args) and it'll save them in a list with qs, and then you can read them into the workspace again with a load function.

Should be relatively easy to do - I might make an attempt.

**Comment by traversc** [comment]
Sure, if you want give it a shot, I'd take a pull request :)

I imagine a pure R implementation will be fine.  During reading, you'd want to check that the top level object is a named list (or possibly use a pairlist, since it's a less common object).

**Comment by traversc** [comment]
Closing, will be incorporated in next update. Thanks!
