### ISSUE TITLE
Add GitHub Topics: compression & others used by fst

### ISSUE THREAD

**Issue by katrinleinweber** [traversc/qs#35]
Thanks for publishing this! In case you'd like to make [your repo more findable](https://github.com/topics/compression), you could [add that topic](https://help.github.com/articles/about-topics/) ;-) And possibly those that [fst](https://github.com/fstpackage/fst) uses, as well. Thank you!

**Comment by traversc** [comment]
Thanks for the great suggestion! I've added some topics.

**Comment by katrinleinweber** [comment]
Thank you :-)
