### ISSUE TITLE
Data-driven error: something went wrong (reading object header)

### ISSUE THREAD

**Issue by glp-p4** [traversc/qs#43]
We have been happily using the qs library for quite some time now, but for the first time we just hit a bug using qserialize that is very data-driven. Specifically, we get this error for some input foo:
```
bar <- qs::qdeserialize(qs::qserialize(foo))
Error in c_qdeserialize(x, use_alt_rep, strict) : 
  something went wrong (reading object header)
```
Unfortunately, we are contractually prohibited from providing the data for foo, or we certainly would. However, we can say that small modifications to the contents of foo cause the error to go away. Is this an issue you are aware of? If so, is there anything we might do to avoid it in the future?

qs version
```
qs_0.21.2 (upgrading didn't resolve the issue)
```
R version:
```
platform       x86_64-redhat-linux-gnu     
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          6.0                         
year           2019                        
month          04                          
day            26                          
svn rev        76424                       
language       R                           
version.string R version 3.6.0 (2019-04-26)
nickname       Planting of a Tree          
```

Thanks!

**Comment by apoliakov** [comment]
Hello folks! I work with @glp-p4 . We have an anonymized repro. Works like this:

```
> load('~/repro.Rdata') #creates the opject 'p3'
> x = qs::qdeserialize(qs::qserialize(p3))
Error in c_qdeserialize(x, use_alt_rep, strict) : 
  something went wrong (reading string header)
```

[repro.Rdata.gz](https://github.com/traversc/qs/files/5278837/repro.Rdata.gz)

**Comment by apoliakov** [comment]
I spent some more time playing with it  - we are just fascinated by it! This repro requires no external data at all:

```
> qs::qdeserialize(qs::qserialize(
      list(a= '....................................................................', 
            b= cbind(integer(246722), as.data.frame(matrix(data=0, nrow=246722, ncol=8))))))
Error in c_qdeserialize(x, use_alt_rep, strict) : 
  something went wrong (reading string header)
```

Removing one of these dots, or removing columns from the matrix makes things work. Internally we at P4 were joking around saying "we've won the lottery".

**Comment by traversc** [comment]
Apologies for any inconvenience, and thanks for bringing this to my attention. 

You're right, it's a sort of lottery bug, but luckily an easy fix. 

Latest commit:
```
devtools::install_github("traversc/qs@712c9760b25fa8bce5c642718d67d8340a34f483")
```

Testing:
```
library(qs)
load("repro.Rdata")
qsave(p3, file = "/tmp/temp.qs", nthreads = 1)
b <- qread("/tmp/temp.qs", nthreads = 1)
b2 <- qread("/tmp/temp.qs", nthreads = 4)

identical(p3, b)
identical(p3, b2)

b3 <- qdeserialize(qserialize(p3))
identical(p3, b3)

x <- list(a= '....................................................................', 
          b= cbind(integer(246722), as.data.frame(matrix(data=0, nrow=246722, ncol=8))))
x2 <- qs::qdeserialize(qs::qserialize(x))
identical(x, x2)
```

Please let me know if it works now, and I'll get this on CRAN soon.

**Comment by apoliakov** [comment]
Thank you @traversc ! Appreciate the quick response.

Will data serialized by this version be readable by an older version of qc (0.21.12) ?

We'll absolutely try it out. We are using qc as part of a big infrastructure - it really helps us move data around quickly - but it will take some time to integrate the fix. We'll do a thorough test and let you know. ETA a couple of days - maybe after the weekend!

Cheers!

**Comment by traversc** [comment]
The error was on the read side not the write side, so I'd advise updating to the latest commit (0.23.3). 

Assuming it works (and I'll keep testing as well), it doesn't take long to get it on CRAN.

**Comment by glp-p4** [comment]
Well, we installed your update and so far it seems to be working well. The issue we experienced doesn't appear to be cropping up anymore. Thanks for the help on this!
