### ISSUE TITLE
example(qsame) assumes exists() is vectorized, but it isn't 

### ISSUE THREAD

**Issue by BillDunlap** [traversc/qs#44]
qs/man/qread.Rd contains several calls to exists() with more than one name given as the 'x' argument:
% grep exists *
qreadm.Rd:exists(c('x1', 'x2')) # returns true
qreadm.Rd:exists(c('x1', 'x2')) # returns true
qsavem.Rd:exists(c('x1', 'x2')) # returns true
qsavem.Rd:exists(c('x1', 'x2')) # returns true

exists(c("x1","x2")) ignores the "x2" and returns the same thing as exists("x1"), without a warning.  Those calls should be replaced by
exists('x1') && exists('x2')

**Comment by traversc** [comment]
Thanks for the report :)

https://github.com/traversc/qs/commit/2f7c73eeeba8263b14ce773b2d119a6ac527f3ec
