### ISSUE TITLE
`qsavem` gives unexpected error when passing a name to its `file` argument in a function

### ISSUE THREAD

**Issue by psychelzh** [traversc/qs#46]
The following script gives an unexpected error. But the name `result_file` actually has a value.

``` r
library(qs)
#> qs v0.23.4.
test <- function() {
  result_file <- "test.qs"
  test1 <- rnorm(100)
  test2 <- rnorm(100)
  qsavem(test1, test2, file = result_file)
}
test()
#> Error in c_qsave(x, file, preset, algorithm, compress_level, shuffle_control, : object 'result_file' not found
```

<sup>Created on 2020-11-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by traversc** [comment]
Thanks for the report. @bryce-chamberlain can you have a look? Maybe checking out what `base::save` does differently?

**Comment by traversc** [comment]
Should be fixed now if you want to give it a shot. 

```
devtools::install_github("traversc/qs")
```

**Comment by bryce-chamberlain** [comment]
@traversc thanks for taking care of this one! December has been a very busy month for me.

**Comment by traversc** [comment]
@bryce-chamberlain No worries! Have a look when you have a chance and see if it's okay.

**Comment by bryce-chamberlain** [comment]
@traversc looks good to me. I checked it and it works as expected. 
@psychelzh can you confirm this is fixed so we can close the issue? thanks!

**Comment by psychelzh** [comment]
@bryce-chamberlain Thanks! Confirmed here. Hope to be released soon.

**Comment by traversc** [comment]
On CRAN now.
