### ISSUE TITLE
Files with ".q" extension causing some issues in RStudio

### ISSUE THREAD

**Issue by antspengy** [traversc/qs#5]
Hi

I've been using qs successfully over the past month but began noticing some strange and quite major slow downs in RStudio in projects that have files saved with ".q" extensions.  This is particularly the case if the .q file is large (i.e. I have a few files that are >300MB).

I logged the issue with RStudio (https://github.com/rstudio/rstudio/issues/4696), and Kevin has explained in his comments why, for historical reasons, files with the ".q" extension are treated similarly to ".s" and ".r" files.  

It looks like they'll fix the issue but I'm just wondering whether in your documentation you may want to consider using a different file extension type because the issue impacts all versions of R Studio so may cause some headaches for other package users.

Thanks
Anthony

**Comment by traversc** [comment]
Thanks for pointing that out, I had no idea!

**Comment by traversc** [comment]
I changed all of the documentation from ".q" to ".qs" in the new version.  Thanks again!
