### ISSUE TITLE
"Warning: end of file not reached, data may be corrupted"

### ISSUE THREAD

**Issue by gevro** [traversc/qs#65]
Hi, I think I found a bug in qs.

qsave for two similar objects did not return any errors.

However, qread for the saved objects gave this error:
"Warning: end of file not reached, data may be corrupted"

How can qsave not return an error, but qread returns an error?

Thanks.

**Comment by traversc** [comment]
Hi, could you send an example?

**Comment by gevro** [comment]
To keep data private, what is your e-mail so I can send you a download link?

**Comment by traversc** [comment]
You can find my email in the maintainer field here: https://github.com/traversc/qs/blob/master/DESCRIPTION

Thanks!

**Comment by traversc** [comment]
Resolved via email
