### ISSUE TITLE
FST works with dataframes

### ISSUE THREAD

**Issue by abalter** [traversc/qs#68]
You should correct this in the readme.

**Comment by traversc** [comment]
I think that is what the readme says. Can you point out where it's incorrect?

**Comment by abalter** [comment]
![image](https://user-images.githubusercontent.com/5349876/167943630-a77036f8-73fb-4e04-a77d-a6d57b3e275c.png)

**Comment by abalter** [comment]
![image](https://user-images.githubusercontent.com/5349876/167943834-37756a80-f658-4055-8936-1599b3517b5a.png)

**Comment by traversc** [comment]
Sorry, I read that sentence 10 times but it sounds correct to me. The issue title "FST works with dataframes" is saying the same thing?

**Comment by abalter** [comment]
Oh shit. I kept reading `data.table`. I swear. Every time I read it, I thought it said `data.table`. I've gotta quit drinking lean while working.

**Comment by traversc** [comment]
No worries!
