### ISSUE TITLE
Binaries through r-universe

### ISSUE THREAD

**Issue by SebKrantz** [traversc/qs#69]
In case this is of interest, I have set up a [fastverse r-universe](https://fastverse.r-universe.dev/) that builds binary versions of the GitHub version of your packages qs and stringfish for MAC and Windows (new binaries are build within an hour of a new commit to your repo). Users can install these binaries using (for qs): 

```
# Enable repository from fastverse
options(repos = c(
    ropensci = 'https://fastverse.r-universe.dev',
    CRAN = 'https://cloud.r-project.org'))

# Download and install qs in R
install.packages('qs')

# Or simply: 
install.packages('qs', repos = c(ropensci = 'https://fastverse.r-universe.dev', 
                                 CRAN = 'https://cloud.r-project.org')) # Needed for dependencies
```

You can also add a Badge to your README.md:

[![qs status badge](https://fastverse.r-universe.dev/badges/qs)](https://fastverse.r-universe.dev)
[![stringfish status badge](https://fastverse.r-universe.dev/badges/stringfish)](https://fastverse.r-universe.dev)

**Comment by traversc** [comment]
Interesting project! Thanks for letting me know about it!
