### ISSUE TITLE
Apple Silicon ? 

### ISSUE THREAD

**Issue by BenjaminDEMAILLE** [traversc/qs#78]
Hi ! 
Do you have some news for Apple Silicon native support ? 
thanks

**Comment by traversc** [comment]
Hi!

Just to be clear Apple Silicon should be natively supported right now, it's just not as optimized as it could be. 

There's a bit of a learning curve and I don't have an Apple M1 / M2 machine I can work with, so at this time it would be difficult for me to implement properly. 

I'll leave this open in case there's anyone with expertise out there who is interested in contributing.
