### ISSUE TITLE
Suggestion : default parameter nthread 

### ISSUE THREAD

**Issue by BenjaminDEMAILLE** [traversc/qs#79]
Hi ! 
is it possible in a future version to do in default 

`nthreads = parallel::detectCores()`

thanks

**Comment by traversc** [comment]
My preference is to keep the default as 1, but this could be an option:

```
options(qs.nthreads = 4)

qsave <- function(..., nthreads = getOption("stringfish.nthreads", 1L)) {
  ...
}
```
Does that work?

**Comment by HenrikBengtsson** [comment]
I downvote the feature request for `nthreads = parallel::detectCores()`, and upvote "keep the default as 1", because of several reasons, which I write about in https://www.jottr.org/2022/12/05/avoid-detectcores/.
