### ISSUE TITLE
Error in c_qread(normalizePath(file, mustWork = FALSE), use_alt_rep, inspect,  :    something went wrong (reading string header)

### ISSUE THREAD

**Issue by leungi** [traversc/qs#8]
I have a batch of output, each containing 100 rows, with a mix of column data types, including list-columns.

Out of 478 outputs, only 1 had generated the subject error on read.

```
> data <- qs::qread(my_files[[i]])
Error in c_qread(normalizePath(file, mustWork = FALSE), use_alt_rep, inspect,  : 
  something went wrong (reading string header)
```

Can this be due to corruption on save? I don't see any warning/error message on save, so it may be useful to have `qs` check file readability (random sampling of rows) on saved object.

**Comment by traversc** [comment]
Yes it sounds like the data got corrupted on save.  If R gets interrupted while saving, it could lead to corruption, but I haven't seen a case that is reproducible.  

Are you saying that it is an error that always happens reproducibly?  If so, do you think you could help me troubleshoot?

**Comment by leungi** [comment]
Thanks for prompt response @traversc.

RAM may not be the issue in this case; the corrupted file is in the middle (file 224) out of the 478.

This is the first time I've had issue with `.qs` file; otherwise, it's been amazing so far 👍 

I can't reproduce the error; using the same data, I was able to save and successfully read back the new `.qs` file.

`qread(my.file.path, use_alt_rep=F)` returns same error.

`qinspect(my.file.path)` returns `TRUE`.

I suppose we'll close this as one of those mystery in life?

**Comment by traversc** [comment]
Do you think it would be possible to send the problematic data?  I'm hoping the data is not too sensitive, and I would really appreciate if we could solve the issue.

**Comment by leungi** [comment]
They are proprietary data; apologies.

I thought of anonymizing the data, but since it's corrupted, I can't open it :anguished:

Unless there's another brute force way to recovering data from the corrupted file...

**Comment by traversc** [comment]
You could use the `qdump` function to output raw unserialized data.  You could then "manually" pull out data, but I suspect it would be more trouble than it's worth, since you'd need to read tons of code to understand the format 😧

If you ever come across corrupted data you can share, please e-mail me @ gmail.

**Comment by leungi** [comment]
`qdump()` does work, but manually decoding the raw data is beyond me :sweat:.

I will take note of future occurrence and email you.

Thanks again for your work!
