### ISSUE TITLE
can't install 'qs' package on remote server CentOS Linux 7 (Core)

### ISSUE THREAD

**Issue by liuxx1996** [traversc/qs#80]
hello,
  I recently try to install the package with command in R: install.packages('qs'), however, it returned error (details bellow).
 anyone can help me?
 thank you!

###############################################################################
my Linux version:
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

###############################################################################
my R version:
platform       x86_64-pc-linux-gnu
arch           x86_64
os             linux-gnu
system         x86_64, linux-gnu
status
major          4
minor          1.1
year           2021
month          08
day            10
svn rev        80725
language       R
version.string R version 4.1.1 (2021-08-10)
nickname       Kick Things

###############################################################################
Error message:
  > install.packages('qs')
trying URL 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/src/contrib/qs_0.25.5.tar.gz'
Content type 'application/octet-stream' length 2148313 bytes (2.0 MB)
==================================================
downloaded 2.0 MB

* installing *source* package ‘qs’ ...
** package ‘qs’ successfully unpacked and MD5 sums checked
** using staged installation
checking for pkg-config... /usr/bin/pkg-config
zstd library not detected -- compiling from source
lz4 library not detected -- compiling from source
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++ -std=gnu++14 -I"/home/liuxinxuan/software/R-4.1.1/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -DRCPP_NO_RTTI -DRCPP_NO_SUGAR -I. -IZSTD -IZSTD/common -IZSTD/decompress -IZSTD/compress -ILZ4  -I'/home/liuxinxuan/software/R-4.1.1/library/Rcpp/include' -I'/home/liuxinxuan/software/R-4.1.1/library/RApiSerialize/include' -I'/home/liuxinxuan/software/R-4.1.1/library/stringfish/include' -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++14 -I"/home/liuxinxuan/software/R-4.1.1/include" -DNDEBUG -DRCPP_USE_UNWIND_PROTECT -DRCPP_NO_RTTI -DRCPP_NO_SUGAR -I. -IZSTD -IZSTD/common -IZSTD/decompress -IZSTD/compress -ILZ4  -I'/home/liuxinxuan/software/R-4.1.1/library/Rcpp/include' -I'/home/liuxinxuan/software/R-4.1.1/library/RApiSerialize/include' -I'/home/liuxinxuan/software/R-4.1.1/library/stringfish/include' -I/usr/local/include   -fpic  -g -O2  -c qs_functions.cpp -o qs_functions.o
In file included from qs_functions.cpp:24:
qs_mt_serialization.h:85:20: error: ‘thread’ is not a member of ‘std’
   std::vector<std::thread> threads;
                    ^~~~~~
qs_mt_serialization.h:85:20: note: ‘std::thread’ is defined in header ‘<thread>’; did you forget to ‘#include <thread>’?
qs_mt_serialization.h:27:1:
+#include <thread>

qs_mt_serialization.h:85:20:
   std::vector<std::thread> threads;
                    ^~~~~~
qs_mt_serialization.h:85:20: error: ‘thread’ is not a member of ‘std’
qs_mt_serialization.h:85:20: note: ‘std::thread’ is defined in header ‘<thread>’; did you forget to ‘#include <thread>’?
qs_mt_serialization.h:85:26: error: template argument 1 is invalid
   std::vector<std::thread> threads;
                          ^
qs_mt_serialization.h:85:26: error: template argument 2 is invalid
qs_mt_serialization.h: In member function ‘void Compress_Thread_Context<compress_env>::worker_thread(unsigned int)’:
qs_mt_serialization.h:94:14: error: ‘std::this_thread’ has not been declared
         std::this_thread::yield();
              ^~~~~~~~~~~
In file included from qs_functions.cpp:24:
qs_mt_serialization.h:105:14: error: ‘std::this_thread’ has not been declared
         std::this_thread::yield();
              ^~~~~~~~~~~
qs_mt_serialization.h:126:14: error: ‘std::this_thread’ has not been declared
         std::this_thread::yield();
              ^~~~~~~~~~~
qs_mt_serialization.h: In member function ‘void Compress_Thread_Context<compress_env>::finish()’:
qs_mt_serialization.h:143:16: error: invalid types ‘int[unsigned int]’ for array subscript
       threads[i].join();
                ^
qs_mt_serialization.h: In constructor ‘Compress_Thread_Context<compress_env>::Compress_Thread_Context(std::ofstream*, unsigned int, QsMetadata)’:
qs_mt_serialization.h:163:15: error: request for member ‘push_back’ in ‘((Compress_Thread_Context<compress_env>*)this)->Compress_Thread_Context<compress_env>::threads’, which is of non-class type ‘int’
       threads.push_back(std::thread(&Compress_Thread_Context::worker_thread, this, i));
               ^~~~~~~~~
qs_mt_serialization.h:163:30: error: ‘thread’ is not a member of ‘std’
       threads.push_back(std::thread(&Compress_Thread_Context::worker_thread, this, i));
                              ^~~~~~
qs_mt_serialization.h:163:30: note: ‘std::thread’ is defined in header ‘<thread>’; did you forget to ‘#include <thread>’?
qs_mt_serialization.h: In member function ‘char* Compress_Thread_Context<compress_env>::get_new_block_ptr()’:
qs_mt_serialization.h:173:12: error: ‘std::this_thread’ has not been declared
       std::this_thread::yield();
            ^~~~~~~~~~~
qs_mt_serialization.h: In member function ‘void Compress_Thread_Context<compress_env>::push_ptr(const char*, uint32_t)’:
qs_mt_serialization.h:195:12: error: ‘std::this_thread’ has not been declared
       std::this_thread::yield();
            ^~~~~~~~~~~
qs_mt_serialization.h: In member function ‘void CompressBuffer_MT<compress_env>::shuffle_push(const char*, uint64_t, uint64_t)’:
qs_mt_serialization.h:297:14: error: ‘std::this_thread’ has not been declared
         std::this_thread::yield();
              ^~~~~~~~~~~
In file included from qs_functions.cpp:26:
qs_mt_deserialization.h: At global scope:
qs_mt_deserialization.h:77:20: error: ‘thread’ is not a member of ‘std’
   std::vector<std::thread> threads;
                    ^~~~~~
qs_mt_deserialization.h:77:20: note: ‘std::thread’ is defined in header ‘<thread>’; did you forget to ‘#include <thread>’?
qs_mt_deserialization.h:1:1:
+#include <thread>
 /* qs - Quick Serialization of R Objects
qs_mt_deserialization.h:77:20:
   std::vector<std::thread> threads;
                    ^~~~~~
qs_mt_deserialization.h:77:20: error: ‘thread’ is not a member of ‘std’
qs_mt_deserialization.h:77:20: note: ‘std::thread’ is defined in header ‘<thread>’; did you forget to ‘#include <thread>’?
qs_mt_deserialization.h:77:26: error: template argument 1 is invalid
   std::vector<std::thread> threads;
                          ^
qs_mt_deserialization.h:77:26: error: template argument 2 is invalid
qs_mt_deserialization.h: In constructor ‘Data_Thread_Context<decompress_env>::Data_Thread_Context(std::ifstream&, unsigned int, QsMetadata)’:
qs_mt_deserialization.h:97:15: error: request for member ‘push_back’ in ‘((Data_Thread_Context<decompress_env>*)this)->Data_Thread_Context<decompress_env>::threads’, which is of non-class type ‘int’
       threads.push_back(std::thread(&Data_Thread_Context::worker_thread, this, i));
               ^~~~~~~~~
qs_mt_deserialization.h:97:30: error: ‘thread’ is not a member of ‘std’
       threads.push_back(std::thread(&Data_Thread_Context::worker_thread, this, i));
                              ^~~~~~
qs_mt_deserialization.h:97:30: note: ‘std::thread’ is defined in header ‘<thread>’; did you forget to ‘#include <thread>’?
qs_mt_deserialization.h: In member function ‘void Data_Thread_Context<decompress_env>::worker_thread(unsigned int)’:
qs_mt_deserialization.h:106:14: error: ‘std::this_thread’ has not been declared
         std::this_thread::yield();
              ^~~~~~~~~~~
qs_mt_deserialization.h:132:14: error: ‘std::this_thread’ has not been declared
         std::this_thread::yield();
              ^~~~~~~~~~~
qs_mt_deserialization.h: In member function ‘void Data_Thread_Context<decompress_env>::finish()’:
qs_mt_deserialization.h:154:16: error: invalid types ‘int[unsigned int]’ for array subscript
       threads[i].join();
                ^
qs_mt_deserialization.h: In member function ‘std::pair<char*, long unsigned int> Data_Thread_Context<decompress_env>::get_block_ptr()’:
qs_mt_deserialization.h:161:47: error: ‘std::this_thread’ has not been declared
     while(data_task[current_block] != 0) std::this_thread::yield();
                                               ^~~~~~~~~~~
qs_mt_deserialization.h:163:47: error: ‘std::this_thread’ has not been declared
     while(data_task[current_block] != 0) std::this_thread::yield();
                                               ^~~~~~~~~~~
qs_mt_deserialization.h: In member function ‘void Data_Thread_Context<decompress_env>::decompress_data_direct(char*)’:
qs_mt_deserialization.h:172:47: error: ‘std::this_thread’ has not been declared
     while(data_task[current_block] != 0) std::this_thread::yield();
                                               ^~~~~~~~~~~
qs_mt_deserialization.h:175:47: error: ‘std::this_thread’ has not been declared
     while(data_task[current_block] != 0) std::this_thread::yield();
                                               ^~~~~~~~~~~
make: *** [qs_functions.o] Error 1
ERROR: compilation failed for package ‘qs’
* removing ‘/home/liuxinxuan/software/R-4.1.1/library/qs’

The downloaded source packages are in
        ‘/tmp/RtmpSrrFvO/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("qs") :
  installation of package ‘qs’ had non-zero exit status

**Comment by traversc** [comment]
"threads" is a standard C++ library, so it's weird that it's not found. 

I have not had trouble installing on Centos 7, if you can give reproducible steps e.g. using a fresh Centos VM I can have a look.
