### ISSUE TITLE
replacement of save.image ?

### ISSUE THREAD

**Issue by BenjaminDEMAILLE** [traversc/qs#81]
Hi ! how can I reproduce the save.image() with qsave ?
thanks in advance

**Comment by traversc** [comment]
Check out `?qsavem` and `?qreadm`, which replaces save and load.

**Comment by kaizen89** [comment]
@traversc Is it possible to use something like  `qsavem(names(.GlobalEnv))`. save.image is using `save(names(.GlobalEnv))` but not `qsavem`.
