### ISSUE TITLE
zstd decompression error - qread()

### ISSUE THREAD

**Issue by wjbsb** [traversc/qs#82]
Hi,

To begining, I want to told you : thank a lot for your package. It upcrease largely my way to save data in R !

I used qsave for every thing I built. 
Today, I have a problem for open a qs file.
I saved object in this qs file from my laptop and I want to read the same file in an other laptop.
I can read qs file in my first laptop : no problem.
I can't read qs file in second laptop, the error message is : 

_Erreur dans qs::qread(file = path_file_qs : zstd decompression error_

I can read other qs file in second laptop. But for this file in particular not...

qs version is the same. 
R version is different : R 4.1.1 (my first laptop) vs R 4.2.0 (my second laptop) 

Do you want an idea ?

Have a nice day !

**Comment by traversc** [comment]
Hi, I am unsure what could be the cause of the issue. Perhaps different versions of zstd installed? And are you using the latest version of qs? What about operating system?

It might be hard to come up with a reproducible example, but if you can put one together I would have a look.

**Comment by wjbsb** [comment]
Hi, 
I aligned zstd version and now it's work ! 

Thanks a lot.
