### ISSUE TITLE
Slowly when using multiple threads

### ISSUE THREAD

**Issue by Yunuuuu** [traversc/qs#86]
```
[R]> system.time(
         ascii_data <- qs::qread("munging/ascii_data.qs", nthreads = 10L)
     )
    user   system  elapsed 
 467.950 1187.845  165.595 

[R]> system.time(
         ascii_data <- qs::qread("munging/ascii_data.qs")
     )
   user  system elapsed 
119.951   5.576 125.522 
```

![image](https://github.com/traversc/qs/assets/19575010/2a8a8680-7f6b-4b2f-ad97-a7bea5662f69)

**Comment by traversc** [comment]
Hi, most of the time is spent serially in R in reprocessing strings. The only thing that gets multithreaded is the decompression. 

Also in the future, please give a reproducible example and complete description.
