### ISSUE TITLE
qread() cannot locate file on cloud?

### ISSUE THREAD

**Issue by cnavery** [traversc/qs#95]
Hello!

I've been moving a pipeline from a server to a cloud server, and wondered if this might be the reason that qread() cannot locate a file in a google bucket? I double checked the path, so I feel certain that I'm pointing it to the right place. 

It might also be some other issue I hadn't considered... Any help troubleshooting would be appreciated!

**Comment by traversc** [comment]
Hi, could you give a brief reproducible example? Not too familiar with google cloud. If it's not mounted as a file system, then that might be the reason.

**Comment by cnavery** [comment]
Sure thing!
It's pretty straight forward, actually. I hardcoded the file path to make sure it was pointing to the correct place.
I do suspect that it has something to do with the file structure, but wanted to check. I might try copying the file from the gs bucket to the persistent disk and seeing if that works. Will report back if it does!

`
library(qs)

#path to google bucket
pheno_file = 'gs://fc-secure-e2ecf24f-82c7-417f-a97a-356801da47e7/pathtofile/AJ_345_UDN_phenotype_file.qs' 

UDN_diseaseHpoMap = qread(pheno_file)

`

**Comment by cnavery** [comment]
Alright, I am back with an update. I was able to copy the data from a google bucket to the persistent disk associated with my cloud environment and this worked.

**Comment by traversc** [comment]
Great! Yeah I think its just a limitation of the file interface in C++. Please feel free to reopen if there is anything else!
