### ISSUE TITLE
segfault: RApiSerialize update requires rebuilding/reinstalling qs from source

### ISSUE THREAD

**Issue by achubaty** [traversc/qs#96]
just dropping a note here for others, that following an update today to `RApiSerialize`, I needed to reinstall `qs` (from source!) to get rid of the following errors on various platforms:

```r
 *** caught segfault ***
address (nil), cause 'memory not mapped'
```

```r
 *** caught segfault ***
address (nil), cause 'invalid permission'
```

**Comment by toomish** [comment]
Same problem:
```
> qs::qsave(df, "data.qs")

 *** caught segfault ***
address 0x19, cause 'memory not mapped'
```
Reinstall `qs` from source helped to get rid of the error.

**Comment by traversc** [comment]
Thanks, yes please re-install qs if you have this issue

**Comment by mattfidler** [comment]
Do you have to reinstall from source or is it simply from CRAN?

**Comment by mattfidler** [comment]
Note for my runnners they install from the mac binaries and it still crashes.

**Comment by achubaty** [comment]
Need to install from source (can be from CRAN or GitHub):

```r
install.packages("qs", type = "source")
## or
remotes::install_github("traversc/qs")
```

For GitHub Actions runners, the easiest thing to do was to install the source from GitHub for this package, e.g.,

```
- uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            traversc/qs
          needs: check
```

**Comment by traversc** [comment]
Thanks for all the reports. New version out on CRAN so hopefully this issue is moot now.
