### ISSUE TITLE
qsavem(list = ls(),file = "environment2.qs",nthreads = 4)  Error

### ISSUE THREAD

**Issue by nolanjj** [traversc/qs#99]
qsavem(list = ls(),file = "environment2.qs",nthreads = 4)
Error in (function (x, file, preset = "high", algorithm = "zstd", compress_level = 4L,  : 
  argument "file" is missing, with no default

but
save(list = ls(),file =  "environment.RData") is OK.

**Comment by traversc** [comment]
Hi, the issue you have is the using the `list` parameter doesn't exist in `qsavem` / `qsave`. Try it without the list parameter.

**Comment by nolanjj** [comment]
> Hi, the issue you have is the `list` parameter doesn't exist in `qsavem` / `qsave`. Try it without the list parameter.

I try it without the list parameter.
![image](https://github.com/traversc/qs/assets/35267241/069233d4-2028-4da0-b8d9-5ec9e89926e4)

them 
![image](https://github.com/traversc/qs/assets/35267241/f2d95798-080a-4c97-a790-acbd826660ad)

**Comment by nolanjj** [comment]
But I found another way!   Speed is so fast ,grateful!
![image](https://github.com/traversc/qs/assets/35267241/a2ec4394-4ec2-45f3-8983-c0e66bdd0012)

**Comment by XIANZHE-LI** [comment]
> But I found another way! Speed is so fast ,grateful! ![image](https://private-user-images.githubusercontent.com/35267241/334245566-a2ec4394-4ec2-45f3-8983-c0e66bdd0012.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NzY3MTgsIm5iZiI6MTcxNjg3NjQxOCwicGF0aCI6Ii8zNTI2NzI0MS8zMzQyNDU1NjYtYTJlYzQzOTQtNGVjMi00NWYzLTg5ODMtYzBlNjZiZGQwMDEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA2MDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MzljNjE3MDU2YjIxOWUwYTg0NGQxOTIxZDhmNDQ5MTJhZTQ3ZTJkZTE1ZTIwNjFiYmU4ZjM3ZWUyYzc1MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ImSz0xeq8xmdxo3vYLPdz1GqR5YfNDBrJqmOmRAImZ0)

学到了
